apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cart-page-rs
  namespace: prathiksha-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      web: cart
  template: #it defines which application tht has to be deployed in a cluster(pod)
    metadata:
      labels:
        web: cart
    spec: #it defines behaviou of the pod and  its containers
      containers:
        - name: cart-container
          image: muralisocial123/cart-page-test:1.0
          ports: 
            - containerPort: 3000
